### ISSUE TITLE
[BUG] "pack" command

### ISSUE THREAD

**Issue by ArK-z1** [brxken128/dexios#218]
Pack feature when `<input>` is a file instead of a folder. It creates and empty file and reports an overflow error

**To Reproduce**
`dexios -p test.txt test.enc`
Error:
`thread 'main' has overflowed its stack`

**Desktop**
 - OS: [Win10 21H2]
 - Precompiled binary.

**[QUESTION]**
What is the sintaxis for the for the `<input>` argument?
For example, this doesn't work:
`dexios pack d:\bin\dir dir.enc`
`dexios pack "d:\bin\dir" dir.enc`
`dexios pack .\dir dir.enc`
`dexios pack ".\dir" dir.enc`
**Error:**
`Error: Unable to read the file in Read mode`

**Comment by brxken128** [comment]
Good catch! I can have this fixed within an hour, and can publish a patch release also.

**Comment by brxken128** [comment]
As for your question, you raise a very good point. I'm not a Windows user myself, but this seems like something that shouldn't be happening. The error originates from `FileStorage`, but it should be able to read Windows paths.

I'll take a deeper look into it shortly.

**Comment by brxken128** [comment]
@pleshevskiy I have a Windows VM, so I'm gonna take a look into the second half. Packing indeed doesn't work, no matter that path I provide it.

**Comment by brxken128** [comment]
@brxken128 Apologies for the ping, but I'd just like to let you know that this has been fixed. It was a combination of:

* Not checking if the input was a directory or a file
* Most importantly (and what resulted in the stack overflow), allocating a full 1MiB array on the stack instead of the heap

This has been resolved, and I can publish v8.8.1 tomorrow at some point.
