### ISSUE TITLE
[BUG] Incompatibility with other tools

### ISSUE THREAD

**Issue by Xanthus58** [brxken128/dexios#278]
**Describe the bug**
Dexios is not compatable with other xchacha applications like [hat.sh](https://hat.sh/) and [picocrypt](https://github.com/HACKERALERT/Picocrypt)

**To Reproduce**
Encrypt a file with dexios and attempt to decrypt it with the other applications

**Expected behavior**
It should be cross-compatable as they use the same scheme

**Screenshots**
![image](https://user-images.githubusercontent.com/66909997/232957574-2860365c-3219-4ae4-807d-da59bec771dd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.8.1

**I have a question if you dont mind.**
My question is this; where does this issue come from? Is it a lack of documentation of a "standardization" for xchacha, are these developers doing it on purpose; or are they just not very good implementations of the algo? If you could point me in the right direction and provide some sources for me to read up on like blog posts wiki pages etc that'd be greatly appreciated.

**Comment by HACKERALERT** [comment]
XChaCha20 is just a cipher. There is much more to an encryption tool than just a cipher -- there needs to be key derivation and authentication, just to mention a few. Each tool uses its own set of algorithms outside of XChaCha20 and store values in their own format. XChaCha20 is standardized, but these individual header formats are not. No, developers don't intentionally try to break things. No, just because tools are not cross-compatible doesn't mean they are bad. No, there is not a lack of documentation, everything is well defined and standardized in the form of RFCs. So the "issue" is that each tool uses its own format that isn't compatible with other tools, although the algorithms used themselves are standardized.

**Comment by Xanthus58** [comment]
Thanks that's incredibly informative and explains it perfectly

**Comment by HACKERALERT** [comment]
@brxken128 Of course, glad to help when I can! Thanks for the donation :)
